IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSSActivity' AND COLUMN_NAME = 'IsMaterialAvailable')
BEGIN
ALTER TABLE ussSSActivity
ADD IsMaterialAvailable BIT NULL
End
