Public Class xaeDefaults
    Inherits xaegDefaults

    Private Sub xaeDefaults_Load(sender As System.Object, e As System.EventArgs) Handles MyBase.Load

        Try
            Me.Record = API.Defaults.Defaults
            If Me.Record Is Nothing Then
                Me.Record = New API.Defaults
            End If
        Catch ex As Exception
            Setup.Log.logError("Error fetching defaults.", ex)
        End Try

        Try
            LoadEnums()
        Catch ex As Exception
            Setup.Log.logError("Error populating enums.", ex)
        End Try

        Try
            Dim jcbl As New Helper.Evolution.LookupLoader(Of Pastel.Evolution.JobTransactionCode)(DefaultTransactionCodeLookupEdit, JobTransactionCodeBindingSource, "idJobTxTp")
        Catch ex As Exception
            Setup.Log.logError("Error setting loader for Job Transaction Codes.", ex)
        End Try

        Try
            Dim plbl As New Helper.Evolution.LookupLoader(Of Pastel.Evolution.PriceList)(DefaultPricelistIDLookUpEdit, PriceListBindingSource, "IDPricelistName")
        Catch ex As Exception
            Setup.Log.logError("Error setting loader for Pricelists.", ex)
        End Try

        Try
            Dim wbl As New Helper.Evolution.LookupLoader(Of Pastel.Evolution.Warehouse)(ManufacturingWarehouseLookupEdit, WarehouseBindingSource, "WhseLink")
        Catch ex As Exception
            Setup.Log.logError("Error setting loader for Warehouses.", ex)
        End Try

        Try
            Dim iibl As New Helper.GUI.LookupBackgroundLoader(Of UniSource.Helper.ActiveRecord.Evolution.StockItem)(InventoryItemLookUpEdit, AddressOf LoadStockItems)
        Catch ex As Exception
            Setup.Log.logError("Error setting loader for Inventory Items.", ex)
        End Try

        Try
            SetNumberingStyles()
        Catch ex As Exception
            Setup.Log.logError("Error setting Numbering Styles.", ex)
        End Try

    End Sub

    Private Function LoadStockItems() As IEnumerable(Of UniSource.Helper.ActiveRecord.Evolution.StockItem)
        Dim crit = NHibernate.Criterion.DetachedCriteria.For(Of UniSource.Helper.ActiveRecord.Evolution.StockItem)()
        crit.Add(NHibernate.Criterion.Expression.Eq("ServiceItem", True))
        crit.Add(NHibernate.Criterion.Expression.Eq("ItemActive", True))
        Return UniSource.Helper.ActiveRecord.Evolution.StockItem.FindAll(crit)
    End Function

    Private Sub LoadEnums()
        PricingMethodLookUpEdit.Properties.DataSource = [Enum].GetValues(GetType(API.PricingMethod))
        JobNumberPrefixTypeLookUpEdit.Properties.DataSource = [Enum].GetValues(GetType(API.PrefixType))
        TemplateNumberPrefixTypeLookupEdit.Properties.DataSource = [Enum].GetValues(GetType(API.PrefixType))
        DeliveryNumberPrefixTypeLookUpEdit.Properties.DataSource = [Enum].GetValues(GetType(API.PrefixType))
        QuoteNumberPrefixTypeLookUpEdit.Properties.DataSource = [Enum].GetValues(GetType(API.PrefixType))
        RequisitionNumberPrefixTypeLookUpEdit.Properties.DataSource = [Enum].GetValues(GetType(API.PrefixType))
        PurchaseOrderNumberPrefixTypeLookUpEdit.Properties.DataSource = [Enum].GetValues(GetType(API.PurchaseOrderPrefixType))
        RevenueCodeMethodLookUpEdit.Properties.DataSource = [Enum].GetValues(GetType(API.RevenueCodeMethod))
        RevenueMethodLookupEdit.Properties.DataSource = [Enum].GetValues(GetType(API.RevenueMethod))
        ERPIntegrationMethodLookupEdit.Properties.DataSource = [Enum].GetValues(GetType(API.ERPIntegrationMethod))
        CostCentreMethodTextEdit.Properties.DataSource = [Enum].GetValues(GetType(API.CostCentreMethod))
        PricelistSourceLookUpEdit.Properties.DataSource = [Enum].GetValues(GetType(API.PricelistSource))
        SellingPriceGPCheckTypeIDLookUpEdit.Properties.DataSource = [Enum].GetValues(GetType(API.GPCheckType))
        SupplierDeliveryNumberPrefixLookUpEdit.Properties.DataSource = [Enum].GetValues(GetType(API.PurchaseOrderPrefixType))
        WarehouseIssuePrefixTypeLookUpEdit.Properties.DataSource = [Enum].GetValues(GetType(API.PrefixType))

        DefaultJobScreenLookUpEdit.Properties.DataSource = [Enum].GetValues(GetType(API.DefaultJobScreen))
        DefaultJobLineScreenLookUpEdit.Properties.DataSource = [Enum].GetValues(GetType(API.DefaultJobLineScreen))
    End Sub

    Private Sub SetNumberingStyles()
        If Me.Record Is Nothing Then Exit Sub

        '' Job Number
        If Me.Record.IsJobNumberAutoGenerated Then
            JobNumberNextNumberSpinEdit.Properties.ReadOnly = False
            If Me.Record.JobNumberPrefixType = API.PrefixType.Default Then
                JobNumberPrefixTextEdit.Properties.ReadOnly = False
            Else
                JobNumberPrefixTextEdit.Properties.ReadOnly = True
            End If
            JobNumberPrefixTypeLookUpEdit.Properties.ReadOnly = False
            JobNumberPaddingSpinEdit.Properties.ReadOnly = False
        Else
            JobNumberNextNumberSpinEdit.Properties.ReadOnly = True
            JobNumberPrefixTextEdit.Properties.ReadOnly = True
            JobNumberPrefixTypeLookUpEdit.Properties.ReadOnly = True
            JobNumberPaddingSpinEdit.Properties.ReadOnly = True
        End If

        '' Template Number
        If Me.Record.IsTemplateNumberAutoGenerated Then
            TemplateNumberNextNumberSpinEdit.Properties.ReadOnly = False
            If Me.Record.TemplateNumberPrefixType = API.PrefixType.Default Then
                TemplateNumberPrefixTextEdit.Properties.ReadOnly = False
            Else
                TemplateNumberPrefixTextEdit.Properties.ReadOnly = True
            End If
            TemplateNumberPrefixTypeLookupEdit.Properties.ReadOnly = False
            TemplateNumberPaddingSpinEdit.Properties.ReadOnly = False
        Else
            TemplateNumberNextNumberSpinEdit.Properties.ReadOnly = True
            TemplateNumberPrefixTextEdit.Properties.ReadOnly = True
            TemplateNumberPrefixTypeLookupEdit.Properties.ReadOnly = True
            TemplateNumberPaddingSpinEdit.Properties.ReadOnly = True
        End If

        '' Quote Number
        If Me.Record.IsQuoteNumberAutoGenerated Then
            QuoteNumberNextNumberSpinEdit.Properties.ReadOnly = False
            If Me.Record.QuoteNumberPrefixType = API.PrefixType.Default Then
                QuoteNumberPrefixTextEdit.Properties.ReadOnly = False
            Else
                QuoteNumberPrefixTextEdit.Properties.ReadOnly = True
            End If
            QuoteNumberPrefixTypeLookUpEdit.Properties.ReadOnly = False
            QuoteNumberPaddingSpinEdit.Properties.ReadOnly = False
        Else
            QuoteNumberNextNumberSpinEdit.Properties.ReadOnly = True
            QuoteNumberPrefixTextEdit.Properties.ReadOnly = True
            QuoteNumberPrefixTypeLookUpEdit.Properties.ReadOnly = True
            QuoteNumberPaddingSpinEdit.Properties.ReadOnly = True
        End If

        '' Delivery Number
        If Me.Record.IsDeliveryNumberAutoGenerated Then
            DeliveryNumberNextNumberSpinEdit.Properties.ReadOnly = False
            If Me.Record.DeliveryNumberPrefixType = API.PrefixType.Default Then
                DeliveryNumberPrefixTextEdit.Properties.ReadOnly = False
            Else
                DeliveryNumberPrefixTextEdit.Properties.ReadOnly = True
            End If
            DeliveryNumberPrefixTypeLookUpEdit.Properties.ReadOnly = False
            DeliveryNumberPaddingSpinEdit.Properties.ReadOnly = False
        Else
            DeliveryNumberNextNumberSpinEdit.Properties.ReadOnly = True
            DeliveryNumberPrefixTextEdit.Properties.ReadOnly = True
            DeliveryNumberPrefixTypeLookUpEdit.Properties.ReadOnly = True
            DeliveryNumberPaddingSpinEdit.Properties.ReadOnly = True
        End If

        '' Requisition Number
        If Me.Record.IsRequisitionNumberAutoGenerated Then
            RequisitionNumberNextNumberSpinEdit.Properties.ReadOnly = False
            If Me.Record.RequisitionNumberPrefixType = API.PrefixType.Default Then
                RequisitionNumberPrefixTextEdit.Properties.ReadOnly = False
            Else
                RequisitionNumberPrefixTextEdit.Properties.ReadOnly = True
            End If
            RequisitionNumberPrefixTypeLookUpEdit.Properties.ReadOnly = False
            RequisitionNumberPaddingSpinEdit.Properties.ReadOnly = False
        Else
            RequisitionNumberNextNumberSpinEdit.Properties.ReadOnly = True
            RequisitionNumberPrefixTextEdit.Properties.ReadOnly = True
            RequisitionNumberPrefixTypeLookUpEdit.Properties.ReadOnly = True
            RequisitionNumberPaddingSpinEdit.Properties.ReadOnly = True
        End If

        '' Warehouse Issue Number
        If Me.Record.isWarehouseIssueNumberAutoGenerated Then
            WarehouseNumberNextNumberSpinEdit.Properties.ReadOnly = False
            If Me.Record.WarehouseIssueNumberPrefixType = API.PrefixType.Default Then
                WarehouseNumberPrefixTextEdit.Properties.ReadOnly = False
            Else
                WarehouseNumberPrefixTextEdit.Properties.ReadOnly = True
            End If
            WarehouseIssuePrefixTypeLookUpEdit.Properties.ReadOnly = False
            WarehouseNumberPaddingSpinEdit.Properties.ReadOnly = False
        Else
            WarehouseNumberNextNumberSpinEdit.Properties.ReadOnly = True
            WarehouseNumberPrefixTextEdit.Properties.ReadOnly = True
            WarehouseIssuePrefixTypeLookUpEdit.Properties.ReadOnly = True
            WarehouseNumberPaddingSpinEdit.Properties.ReadOnly = True
        End If

        '' PurchaseOrder Number
        If Me.Record.IsPurchaseOrderNumberAutoGenerated Then
            PurchaseOrderNumberNextNumberSpinEdit.Properties.ReadOnly = False
            PurchaseOrderNumberPrefixTypeLookUpEdit.Properties.ReadOnly = False
            PurchaseOrderNumberPaddingSpinEdit.Properties.ReadOnly = False
            If Me.Record.PurchaseOrderNumberPrefixType = API.PurchaseOrderPrefixType.Default Then
                PurchaseOrderNumberPrefixTextEdit.Properties.ReadOnly = False
            ElseIf Me.Record.PurchaseOrderNumberPrefixType = API.PurchaseOrderPrefixType.ERP Then
                PurchaseOrderNumberPrefixTextEdit.Properties.ReadOnly = True
                PurchaseOrderNumberNextNumberSpinEdit.Properties.ReadOnly = True
                PurchaseOrderNumberPrefixTextEdit.Properties.ReadOnly = True
                PurchaseOrderNumberPaddingSpinEdit.Properties.ReadOnly = True
            Else
                PurchaseOrderNumberPrefixTextEdit.Properties.ReadOnly = True
            End If
        Else
            PurchaseOrderNumberNextNumberSpinEdit.Properties.ReadOnly = True
            PurchaseOrderNumberPrefixTextEdit.Properties.ReadOnly = True
            PurchaseOrderNumberPrefixTypeLookUpEdit.Properties.ReadOnly = True
            PurchaseOrderNumberPaddingSpinEdit.Properties.ReadOnly = True
        End If

        ' Supplier Delivery Note Number
        If Me.Record.isSupplierDeliveryNoteNumberAutoGenerated Then
            SupplierDeliveryNoteNumberSpinEdit.Properties.ReadOnly = False
            SupplierDeliveryNumberPrefixLookUpEdit.Properties.ReadOnly = False
            SupplierDeliveryNumberPaddingSpinEdit.Properties.ReadOnly = False
            If Me.Record.SupplierDeliveryNotePrefixType = API.PurchaseOrderPrefixType.Default Then
                SupplierDeliveryNoteNumberPrefixTextEdit.Properties.ReadOnly = False
            ElseIf Me.Record.SupplierDeliveryNotePrefixType = API.PurchaseOrderPrefixType.ERP Then
                SupplierDeliveryNoteNumberPrefixTextEdit.Properties.ReadOnly = True
                SupplierDeliveryNoteNumberSpinEdit.Properties.ReadOnly = True
                SupplierDeliveryNoteNumberPrefixTextEdit.Properties.ReadOnly = True
                SupplierDeliveryNumberPaddingSpinEdit.Properties.ReadOnly = True
            Else
                SupplierDeliveryNoteNumberPrefixTextEdit.Properties.ReadOnly = True
            End If
        Else
            SupplierDeliveryNoteNumberSpinEdit.Properties.ReadOnly = True
            SupplierDeliveryNoteNumberPrefixTextEdit.Properties.ReadOnly = True
            SupplierDeliveryNumberPrefixLookUpEdit.Properties.ReadOnly = True
            SupplierDeliveryNumberPaddingSpinEdit.Properties.ReadOnly = True
        End If

    End Sub

    Private Sub IsJobNumberAutoGeneratedCheckEdit_CheckedChanged(sender As System.Object, e As System.EventArgs) Handles IsJobNumberAutoGeneratedCheckEdit.CheckStateChanged
        Me.Record.IsJobNumberAutoGenerated = IsJobNumberAutoGeneratedCheckEdit.Checked
        Try
            SetNumberingStyles()
        Catch ex As Exception
            Setup.Log.logError("Error setting Numbering Styles.", ex)
        End Try
    End Sub

    Private Sub IsTemplateNumberAutoGeneratedCheckEdit_CheckedChanged(sender As System.Object, e As System.EventArgs) Handles IsTemplateNumberAutoGeneratedCheckEdit.CheckStateChanged
        Me.Record.IsTemplateNumberAutoGenerated = IsTemplateNumberAutoGeneratedCheckEdit.Checked
        Try
            SetNumberingStyles()
        Catch ex As Exception
            Setup.Log.logError("Error setting Numbering Styles.", ex)
        End Try
    End Sub

    Private Sub IsQuoteNumberAutoGeneratedCheckEdit_CheckedChanged(sender As System.Object, e As System.EventArgs) Handles IsQuoteNumberAutoGeneratedCheckEdit.CheckStateChanged
        Me.Record.IsQuoteNumberAutoGenerated = IsQuoteNumberAutoGeneratedCheckEdit.Checked
        Try
            SetNumberingStyles()
        Catch ex As Exception
            Setup.Log.logError("Error setting Numbering Styles.", ex)
        End Try
    End Sub

    Private Sub IsDeliveryNumberAutoGeneratedCheckEdit_CheckedChanged(sender As System.Object, e As System.EventArgs) Handles IsDeliveryNumberAutoGeneratedCheckEdit.CheckStateChanged
        Me.Record.IsDeliveryNumberAutoGenerated = IsDeliveryNumberAutoGeneratedCheckEdit.Checked
        Try
            SetNumberingStyles()
        Catch ex As Exception
            Setup.Log.logError("Error setting Numbering Styles.", ex)
        End Try
    End Sub

    Private Sub IsRequisitionNumberAutoGeneratedCheckEdit_CheckedChanged(sender As System.Object, e As System.EventArgs) Handles IsRequisitionNumberAutoGeneratedCheckEdit.CheckStateChanged
        Me.Record.IsRequisitionNumberAutoGenerated = IsRequisitionNumberAutoGeneratedCheckEdit.Checked
        Try
            SetNumberingStyles()
        Catch ex As Exception
            Setup.Log.logError("Error setting Numbering Styles.", ex)
        End Try
    End Sub
    Private Sub IsWarehouseNumberAutoGeneratedCheckEdit_CheckedChanged(sender As System.Object, e As System.EventArgs) Handles IsRequisitionNumberAutoGeneratedCheckEdit.CheckStateChanged
        Me.Record.isWarehouseIssueNumberAutoGenerated = IsWarehouseNumberAutoGeneratedCheckEdit.Checked
        Try
            SetNumberingStyles()
        Catch ex As Exception
            Setup.Log.logError("Error setting Numbering Styles.", ex)
        End Try
    End Sub

    Private Sub IsPurchaseOrderNumberAutoGeneratedCheckEdit_CheckedChanged(sender As System.Object, e As System.EventArgs) Handles IsPurchaseOrderNumberAutoGeneratedCheckEdit.CheckStateChanged
        Me.Record.IsPurchaseOrderNumberAutoGenerated = IsPurchaseOrderNumberAutoGeneratedCheckEdit.Checked
        Try
            SetNumberingStyles()
        Catch ex As Exception
            Setup.Log.logError("Error setting Numbering Styles.", ex)
        End Try
    End Sub

    Private Sub JobNumberPrefixTypeLookUpEdit_EditValueChanged(sender As System.Object, e As System.EventArgs) Handles JobNumberPrefixTypeLookUpEdit.EditValueChanged
        If Me.Record IsNot Nothing Then
            Me.Record.JobNumberPrefixType = JobNumberPrefixTypeLookUpEdit.EditValue
            Try
                SetNumberingStyles()
            Catch ex As Exception
                Setup.Log.logError("Error setting Numbering Styles.", ex)
            End Try
        End If
    End Sub

    Private Sub TemplateNumberPrefixTypeLookupEdit_EditValueChanged(sender As System.Object, e As System.EventArgs) Handles TemplateNumberPrefixTypeLookupEdit.EditValueChanged
        If Me.Record IsNot Nothing Then
            Me.Record.TemplateNumberPrefixType = CType(TemplateNumberPrefixTypeLookupEdit.EditValue, API.PrefixType)
            Try
                SetNumberingStyles()
            Catch ex As Exception
                Setup.Log.logError("Error setting Numbering Styles.", ex)
            End Try
        End If
    End Sub

    Private Sub DeliveryNumberPrefixTypeLookUpEdit_EditValueChanged(sender As System.Object, e As System.EventArgs) Handles DeliveryNumberPrefixTypeLookUpEdit.EditValueChanged
        If Me.Record IsNot Nothing Then
            Me.Record.DeliveryNumberPrefixType = IIf(IsDBNull(DeliveryNumberPrefixTypeLookUpEdit.EditValue), Nothing, DeliveryNumberPrefixTypeLookUpEdit.EditValue)
            Try
                SetNumberingStyles()
            Catch ex As Exception
                Setup.Log.logError("Error setting Numbering Styles.", ex)
            End Try
        End If
    End Sub

    Private Sub QuoteNumberPrefixTypeLookUpEdit_EditValueChanged(sender As System.Object, e As System.EventArgs) Handles QuoteNumberPrefixTypeLookUpEdit.EditValueChanged
        If Me.Record IsNot Nothing Then
            Me.Record.QuoteNumberPrefixType = IIf(IsDBNull(QuoteNumberPrefixTypeLookUpEdit.EditValue), Nothing, QuoteNumberPrefixTypeLookUpEdit.EditValue)
            Try
                SetNumberingStyles()
            Catch ex As Exception
                Setup.Log.logError("Error setting Numbering Styles.", ex)
            End Try
        End If
    End Sub

    Private Sub RequisitionNumberPrefixTypeLookUpEdit_EditValueChanged(sender As System.Object, e As System.EventArgs) Handles RequisitionNumberPrefixTypeLookUpEdit.EditValueChanged
        If Me.Record IsNot Nothing Then
            Me.Record.RequisitionNumberPrefixType = IIf(IsDBNull(RequisitionNumberPrefixTypeLookUpEdit.EditValue), Nothing, RequisitionNumberPrefixTypeLookUpEdit.EditValue)
            Try
                SetNumberingStyles()
            Catch ex As Exception
                Setup.Log.logError("Error setting Numbering Styles.", ex)
            End Try
        End If
    End Sub


    Private Sub WarehouseIssuePrefixTypeLookUpEdit_EditValueChanged(sender As System.Object, e As System.EventArgs) Handles WarehouseIssuePrefixTypeLookUpEdit.EditValueChanged
        If Me.Record IsNot Nothing Then
            'Me.Record.WarehouseIssuePrefixType = IIf(IsDBNull(WarehouseIssuePrefixTypeLookUpEdit.EditValue), Nothing, WarehouseIssuePrefixTypeLookUpEdit.EditValue)
            Me.Record.WarehouseIssueNumberPrefixType = IIf(IsDBNull(WarehouseIssuePrefixTypeLookUpEdit.EditValue), Nothing, WarehouseIssuePrefixTypeLookUpEdit.EditValue)
            Try
                SetNumberingStyles()
            Catch ex As Exception
                Setup.Log.logError("Error setting Numbering Styles.", ex)
            End Try
        End If
    End Sub


    Private Sub PurchaseOrderNumberPrefixTypeLookUpEdit_EditValueChanged(sender As System.Object, e As System.EventArgs) Handles PurchaseOrderNumberPrefixTypeLookUpEdit.EditValueChanged
        If Me.Record IsNot Nothing Then
            Me.Record.PurchaseOrderNumberPrefixType = IIf(IsDBNull(PurchaseOrderNumberPrefixTypeLookUpEdit.EditValue), Nothing, PurchaseOrderNumberPrefixTypeLookUpEdit.EditValue)
            Try
                SetNumberingStyles()
            Catch ex As Exception
                Setup.Log.logError("Error setting Numbering Styles.", ex)
            End Try
        End If
    End Sub

    Private Sub RevenueMethodLookupEdit_EditValueChanged(sender As System.Object, e As System.EventArgs) Handles RevenueMethodLookupEdit.EditValueChanged
        If CType(IIf(IsDBNull(RevenueMethodLookupEdit.EditValue), Nothing, RevenueMethodLookupEdit.EditValue), API.RevenueMethod) <> API.RevenueMethod.None Then
            RevenueCodeMethodLookUpEdit.Properties.ReadOnly = False
        Else
            RevenueCodeMethodLookUpEdit.Properties.ReadOnly = True
        End If
        If CType(IIf(IsDBNull(RevenueCodeMethodLookUpEdit.EditValue), Nothing, RevenueCodeMethodLookUpEdit.EditValue), API.RevenueCodeMethod) = API.RevenueCodeMethod.Default Then
            DefaultRevenueCodeTextEdit.Properties.ReadOnly = False
        Else
            DefaultRevenueCodeTextEdit.Properties.ReadOnly = True
        End If
    End Sub

    Private Sub RevenueCodeMethodLookUpEdit_EditValueChanged(sender As System.Object, e As System.EventArgs) Handles RevenueCodeMethodLookUpEdit.EditValueChanged
        If CType(IIf(IsDBNull(RevenueCodeMethodLookUpEdit.EditValue), Nothing, RevenueCodeMethodLookUpEdit.EditValue), API.RevenueCodeMethod) = API.RevenueCodeMethod.Default Then
            DefaultRevenueCodeTextEdit.Properties.ReadOnly = False
        Else
            DefaultRevenueCodeTextEdit.Properties.ReadOnly = True
        End If
    End Sub

    Private Sub ERPIntegrationMethodLookupEdit_EditValueChanged(sender As System.Object, e As System.EventArgs) Handles ERPIntegrationMethodLookupEdit.EditValueChanged
        If CType(IIf(IsDBNull(ERPIntegrationMethodLookupEdit.EditValue), Nothing, ERPIntegrationMethodLookupEdit.EditValue), API.ERPIntegrationMethod) = API.ERPIntegrationMethod.JobCard Then
            CostCentreMethodTextEdit.Properties.ReadOnly = False
            DefaultTransactionCodeLookupEdit.Properties.ReadOnly = False
            JobCardCreateBudgetLinesCheckEdit.Properties.ReadOnly = False
            JobCardCreatePurchaseOrdersCheckEdit.Properties.ReadOnly = False
            JobCardCreateRecoveryLinesCheckEdit.Properties.ReadOnly = False
            JobCardCreateRequisitionLinesCheckEdit.Properties.ReadOnly = False
            RevenueMethodLookupEdit.Properties.ReadOnly = False
            RevenueCodeMethodLookUpEdit.Properties.ReadOnly = False
            DefaultRevenueCodeTextEdit.Properties.ReadOnly = False
        Else
            CostCentreMethodTextEdit.Properties.ReadOnly = True
            DefaultTransactionCodeLookupEdit.Properties.ReadOnly = True
            JobCardCreateBudgetLinesCheckEdit.Properties.ReadOnly = True
            JobCardCreatePurchaseOrdersCheckEdit.Properties.ReadOnly = True
            JobCardCreateRecoveryLinesCheckEdit.Properties.ReadOnly = True
            JobCardCreateRequisitionLinesCheckEdit.Properties.ReadOnly = True
            RevenueMethodLookupEdit.Properties.ReadOnly = True
            RevenueCodeMethodLookUpEdit.Properties.ReadOnly = True
            DefaultRevenueCodeTextEdit.Properties.ReadOnly = True
        End If
    End Sub

    Private Sub SupplierDeliveryNumberAutoGeneratedCheckEdit_CheckedChanged(sender As System.Object, e As System.EventArgs) Handles SupplierDeliveryNumberAutoGeneratedCheckEdit.CheckedChanged
        Me.Record.isSupplierDeliveryNoteNumberAutoGenerated = SupplierDeliveryNumberAutoGeneratedCheckEdit.Checked
        Try
            SetNumberingStyles()
        Catch ex As Exception
            Setup.Log.logError("Error setting Numbering Styles for Supplier Delivery Number.", ex)
        End Try
    End Sub

    Private Sub SupplierDeliveryNumberPrefixLookUpEdit_EditValueChanged(sender As System.Object, e As System.EventArgs) Handles SupplierDeliveryNumberPrefixLookUpEdit.EditValueChanged
        If Me.Record IsNot Nothing Then
            Me.Record.SupplierDeliveryNotePrefixType = IIf(IsDBNull(SupplierDeliveryNumberPrefixLookUpEdit.EditValue), Nothing, SupplierDeliveryNumberPrefixLookUpEdit.EditValue)
            Try
                SetNumberingStyles()
            Catch ex As Exception
                Setup.Log.logError("Error setting Numbering Styles.", ex)
            End Try
        End If
    End Sub

    Private Sub SpinEdit1_EditValueChanged(sender As System.Object, e As System.EventArgs) Handles SpinEdit1.EditValueChanged

    End Sub
End Class

Public Class xaegDefaults
    Inherits UniSource.Helper.ActiveRecord.xfAddEdit(Of API.Defaults)
End Class