CREATE TABLE [dbo].[ussSFJobFunctionControl](
	[JobFunctionID] [int] NOT NULL,
	[Password] [nvarchar](255) NULL,
 CONSTRAINT [PK_ussSFJobFunctionControl] PRIMARY KEY CLUSTERED 
(
	[JobFunctionID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]