alter table ussSFDefaults
add SupplierDeliveryNotePrefix nvarchar(10) null,
    SupplierDeliveryNotePrefixTypeID int null,
	SupplierDeliveryNotePadding int default 0,
	SupplierDeliveryNoteNextNumber int null,
	isSupplierDeliveryNoteNumberAutoGenerated bit default 0