IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFJobStageReport' AND COLUMN_NAME = 'IsAutomatic')
BEGIN
ALTER TABLE ussSFJobStageReport ADD IsAutomatic bit
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFJobStageReport' AND COLUMN_NAME = 'IsReportOnListScreen')
BEGIN
ALTER TABLE ussSFJobStageReport ADD IsReportOnListScreen bit
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFJobStageReport' AND COLUMN_NAME = 'IsReportOnEditScreen')
BEGIN
ALTER TABLE ussSFJobStageReport ADD IsReportOnEditScreen bit
END