IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFJob' AND COLUMN_NAME = 'PriceCheckNumber')
BEGIN
ALTER TABLE ussSFJob ADD  PriceCheckNumber varchar(20)
End

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFJob' AND COLUMN_NAME = 'SerialNumber')
BEGIN
ALTER TABLE ussSFJob ADD  SerialNumber nvarchar(100)
End

