IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'DefaultJobScreenID')
BEGIN
ALTER TABLE ussSFDefaults ADD  DefaultJobScreenID int
End

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'DefaultJobLineScreenID')
BEGIN
ALTER TABLE ussSFDefaults ADD  DefaultJobLineScreenID int
End

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'SupervisorPassword')
BEGIN
ALTER TABLE ussSFDefaults ADD  SupervisorPassword bit
End

