IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSSArtisan' AND COLUMN_NAME = 'Password')
BEGIN
ALTER TABLE ussSSArtisan ADD [Password] nvarchar(255)
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSSArtisan' AND COLUMN_NAME = 'ChecklistID')
BEGIN
ALTER TABLE ussSSArtisan ADD ChecklistID nvarchar(255)
END
