CREATE TABLE [dbo].[ussSFJobStageFunction](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[JobStageID] [int] NULL,
	[JobFunctionID] [int] NULL,
 CONSTRAINT [PK_ussSFJobStageFunction] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]