IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFJob' AND COLUMN_NAME = 'IsCancelled')
BEGIN
ALTER TABLE ussSFJob
ADD IsCancelled bit null DEFAULT 0
End

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFJob' AND COLUMN_NAME = 'CancelAgentID')
BEGIN
ALTER TABLE ussSFJob
ADD CancelAgentID integer null 
End

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFJob' AND COLUMN_NAME = 'CancelReasonID')
BEGIN
ALTER TABLE ussSFJob
ADD CancelReasonID integer null 
End

