IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFJobStage' AND COLUMN_NAME = 'ValidateActiveJobsAsset')
BEGIN
ALTER TABLE ussSFJobStage ADD ValidateActiveJobsAsset bit
END