IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFPaymentRun' AND COLUMN_NAME = 'PaymentFrequencyID')
BEGIN
ALTER TABLE ussSFPaymentRun ADD  PaymentFrequencyID int
End

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFPaymentRun' AND COLUMN_NAME = 'CompanyBranchID')
BEGIN
ALTER TABLE ussSFPaymentRun ADD  CompanyBranchID int
End