
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'MaritalStatusUDF')
BEGIN
ALTER TABLE ussSFDefaults ADD  MaritalStatusUDF  nvarchar(50)
End
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'GenderUDF')
BEGIN
ALTER TABLE ussSFDefaults ADD  GenderUDF nvarchar(50)
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'AccountNumberUDF')
BEGIN
ALTER TABLE ussSFDefaults ADD   AccountNumberUDF nvarchar(50)
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'PassportNumberUDF')
BEGIN
ALTER TABLE ussSFDefaults ADD   PassportNumberUDF nvarchar(50)
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'AccountHolderNameUDF')
BEGIN
ALTER TABLE ussSFDefaults ADD   AccountHolderNameUDF nvarchar(Max)
END
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'BranchCodeUDF')
BEGIN
ALTER TABLE ussSFDefaults ADD   BranchCodeUDF nvarchar(50)
END
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'TaxCalUDF')
BEGIN
ALTER TABLE ussSFDefaults ADD   TaxCalUDF nvarchar(50)
END
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'BankNameUDF')
BEGIN
ALTER TABLE ussSFDefaults ADD  BankNameUDF nvarchar(50)
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'AccountTypeUDF')
BEGIN
ALTER TABLE ussSFDefaults ADD  AccountTypeUDF nvarchar(50)
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'CurrencyUDF')
BEGIN
ALTER TABLE ussSFDefaults ADD  CurrencyUDF nvarchar(50)
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'PayByUDF')
BEGIN
ALTER TABLE ussSFDefaults ADD  PayByUDF nvarchar(50)
END
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'TaxStartDateUDF')
BEGIN
ALTER TABLE ussSFDefaults ADD  TaxStartDateUDF nvarchar(50)
END
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'UIFUDF')
BEGIN
ALTER TABLE ussSFDefaults ADD  UIFUDF nvarchar(50)
END
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'DateRegisteredUDF')
BEGIN
ALTER TABLE ussSFDefaults ADD  DateRegisteredUDF nvarchar(50)
END
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'PaymentFrequencyUDF')
BEGIN
ALTER TABLE ussSFDefaults ADD  PaymentFrequencyUDF nvarchar(50)
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'SANCReiptNoUDF')
BEGIN
ALTER TABLE ussSFDefaults ADD  SANCReiptNoUDF nvarchar(50)
END
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'SANCRefNumberUDF')
BEGIN
ALTER TABLE ussSFDefaults ADD  SANCRefNumberUDF nvarchar(50)
END
--customer defaults

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'HospitalNumberUDF')
BEGIN
ALTER TABLE ussSFDefaults ADD  HospitalNumberUDF nvarchar(50)
END
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'CommissionUDF')
BEGIN
ALTER TABLE ussSFDefaults ADD  CommissionUDF nvarchar(50)
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'PlanUDF')
BEGIN
ALTER TABLE ussSFDefaults ADD  PlanUDF nvarchar(50)
END
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'DefaultHoursUDF')
BEGIN
ALTER TABLE ussSFDefaults ADD  DefaultHoursUDF nvarchar(50)
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'EmployeeImportCodeUDF')
BEGIN
ALTER TABLE ussSFDefaults ADD  EmployeeImportCodeUDF nvarchar(50)
END












