IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFJob' AND COLUMN_NAME = 'SourceID')
BEGIN
ALTER TABLE ussSFJob ADD SourceID int
END


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFJob' AND COLUMN_NAME = 'ImportDate')
BEGIN
ALTER TABLE ussSFJob ADD ImportDate date
END

