IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'FilterInventoryOnGroup')
BEGIN
ALTER TABLE ussSFDefaults ADD  FilterInventoryOnGroup bit
End
