IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFJob' AND COLUMN_NAME = 'SupplierQuantityDelivered')
BEGIN
ALTER TABLE ussSFJob
ADD SupplierQuantityDelivered Integer NULL DEFAULT 0
End