IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'IsLineDiscountReadOnly')
BEGIN
ALTER TABLE ussSFDefaults ADD  IsLineDiscountReadOnly bit
End

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'IsHeaderDiscountReadOnly')
BEGIN
ALTER TABLE ussSFDefaults ADD  IsHeaderDiscountReadOnly bit
End

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'DefaultDiscountMethodID')
BEGIN
ALTER TABLE ussSFDefaults ADD  DefaultDiscountMethodID int
End