IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFJoblineTime' AND COLUMN_NAME = 'PaymentAmount')
BEGIN
ALTER TABLE ussSFJoblineTime ADD PaymentAmount float
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFJoblineTime' AND COLUMN_NAME = 'IgnoreValidation')
BEGIN
ALTER TABLE ussSFJoblineTime ADD  IgnoreValidation bit 
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFJoblineTime' AND COLUMN_NAME = 'IgnoreTimeValidation')
BEGIN
ALTER TABLE ussSFJoblineTime ADD  IgnoreTimeValidation bit 
END