IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFPaymentRunTypes' AND COLUMN_NAME = 'PayRollCode')
BEGIN
ALTER TABLE ussSFPaymentRunTypes ADD  PayRollCode nvarchar(255)
End