IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFJobline' AND COLUMN_NAME = 'IsCancelled')
BEGIN
ALTER TABLE ussSFJobline ADD IsCancelled bit Null
END


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFJobline' AND COLUMN_NAME = 'CancelledReason')
BEGIN
ALTER TABLE ussSFJobline ADD CancelledReason nvarchar(max) Null
END


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFJobline' AND COLUMN_NAME = 'CancelledUser')
BEGIN
ALTER TABLE ussSFJobline ADD CancelledUser nvarchar(max) Null
END





