CREATE TABLE [dbo].[ussSFPaymentRunTypes](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[Code] nvarchar(255) NULL,
	[Description] nvarchar(255) NULL,
	[RateTypeID] Integer NULL
 CONSTRAINT [PK_ussSFPaymentRunTypes] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]