IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFJobTemplate' AND COLUMN_NAME = 'UseTemplatePricing')
BEGIN
ALTER TABLE ussSFJobTemplate ADD UseTemplatePricing bit
END
