IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'FileSaveDefault')
BEGIN
ALTER TABLE ussSFDefaults ADD  FileSaveDefault nvarchar(MAX)
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'PrintInvoiceUDF')
BEGIN
ALTER TABLE ussSFDefaults ADD  PrintInvoiceUDF nvarchar(50)
END
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'EmailInvoiceUDF')
BEGIN
ALTER TABLE ussSFDefaults ADD  EmailInvoiceUDF nvarchar(50)
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'ProformaInvoiceUDF')
BEGIN
ALTER TABLE ussSFDefaults ADD  ProformaInvoiceUDF nvarchar(50)
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'IncludeExcelInvoiceUDF')
BEGIN
ALTER TABLE ussSFDefaults ADD  IncludeExcelInvoiceUDF nvarchar(50)
END
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'EmailProformaInvoiceUDF')
BEGIN
ALTER TABLE ussSFDefaults ADD  EmailProformaInvoiceUDF nvarchar(50)
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'EmailFrom')
BEGIN
ALTER TABLE ussSFDefaults ADD  EmailFrom nvarchar(255)
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME ='EmailSmtpClient')
BEGIN
ALTER TABLE ussSFDefaults ADD EmailSmtpClient nvarchar(255)
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'EmailPort')
BEGIN
ALTER TABLE ussSFDefaults ADD  EmailPort nvarchar(255)
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'EmailEnableSsl')
BEGIN
ALTER TABLE ussSFDefaults ADD  EmailEnableSsl nvarchar(255)
END
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'EmailUserName')
BEGIN
ALTER TABLE ussSFDefaults ADD  EmailUserName nvarchar(255)
END
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'EmailPassword')
BEGIN
ALTER TABLE ussSFDefaults ADD  EmailPassword nvarchar(255)
END





