
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'PricelistNameSource')
BEGIN
ALTER TABLE ussSFDefaults ADD  PricelistNameSource  int 
End
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'IsWarehouseUsed')
BEGIN
ALTER TABLE ussSFDefaults ADD  IsWarehouseUsed bit
END
