IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFJobStage' AND COLUMN_NAME = 'IsCustomerOnHoldChecked')
BEGIN
ALTER TABLE ussSFJobStage ADD IsCustomerOnHoldChecked bit
END