IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'SellingPriceGPCheckTypeID')
BEGIN
ALTER TABLE ussSFDefaults ADD SellingPriceGPCheckTypeID nvarchar(255)
END

