IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'EmployeeDummyUDF')
BEGIN
ALTER TABLE ussSFDefaults ADD  EmployeeDummyUDF nvarchar(255)
End

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'EmployeeCompanyUDF')
BEGIN
ALTER TABLE ussSFDefaults ADD  EmployeeCompanyUDF nvarchar(255)
End

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'SANCYear')
BEGIN
ALTER TABLE ussSFDefaults ADD  SANCYear integer
End


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'EmployeeImportCode2UDF')
BEGIN
ALTER TABLE ussSFDefaults ADD  EmployeeImportCode2UDF nvarchar(255)
End


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'EmployeeImportCode3UDF')
BEGIN
ALTER TABLE ussSFDefaults ADD  EmployeeImportCode3UDF nvarchar(255)
End


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'EmployeeImportCode4UDF')
BEGIN
ALTER TABLE ussSFDefaults ADD  EmployeeImportCode4UDF nvarchar(255)
End


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ussSFDefaults' AND COLUMN_NAME = 'EmployeeImportCode5UDF')
BEGIN
ALTER TABLE ussSFDefaults ADD  EmployeeImportCode5UDF nvarchar(255)
End